update

diff --git a/utils b/utils
--- a/utils
+++ b/utils
@@ -1,64 +1,65 @@
 # shellcheck disable=SC2148,SC1090,SC2068
 
 ask() {
-read -r -p "${1} [y/N]" answer
-[[ "$answer" =~ [yY].* ]] && $2 && return 0
-return 1
+    tput civis
+    read -r -p "${1} [y/N] " answer
+    tput cnorm
+    [[ "$answer" =~ [yY].* ]] && { $2; return $?; }
 }
 
 err() {
-echo -e "$1" >&2
-exit "$2"
+    echo -e "$1" >&2
+    exit "$2"
 }
 
 warning() {
-echo -e "$1" >&2
+    echo -e "$1" >&2
 }
 
 checkuser() {
-[[ $UID == "0" ]] || err "You are not root." "1"
+    [[ $UID == "0" ]] || err "You are not root." "1"
 }
 
 os() {
-declare -r distro=$(grep -e '^ID=' /etc/os-release \
-    | cut -d = -f 2 | sed -e 's/[[:punct:]]//g' \
-    | tr "[:upper:]" "[:lower:]")
-echo "$distro"
+    declare -r distro=$(grep -e '^ID=' /etc/os-release \
+        | cut -d = -f 2 | sed -e 's/[[:punct:]]//g' \
+        | tr "[:upper:]" "[:lower:]")
+    echo "$distro"
 }
 
 # Usage: install_pkg <package> <package> ...
 install_pkg() {
-echo -e "\nInstalling $*..."
-case $(os) in
-    centos | fedora)
-        yum -y install $@ || dnf -y install $@ || return 3
-        sleep 1
-        ;;
-    ubuntu|debian)
-        apt update
-        apt -y install "$@" || return 3
-        sleep 1
-        ;;
-    manjaro|arch*)
-        pacman -Sy --noconfirm $@ || return 3
-        sleep 1
-        ;;
-esac
+    echo -e "\nInstalling $*..."
+    case $(os) in
+        centos | fedora)
+            yum -y install $@ || dnf -y install $@ || return 3
+            sleep 1
+            ;;
+        ubuntu|debian)
+            apt update
+            apt -y install "$@" || return 3
+            sleep 1
+            ;;
+        manjaro|arch*)
+            pacman -Sy --noconfirm $@ || return 3
+            sleep 1
+            ;;
+    esac
 }
 
 # Usage: dependency_check <package> <package> ...
 dependency_check() {
-while (( $# > 0 )); do
-    echo -en "Dependency check for $1 ..."
-    if ! $1 --version > /dev/null 2>&1 && \
-        ! $1 -v > /dev/null 2>&1 && \
-        ! $1 --help > /dev/null 2>&1; then
-        echo -e "FAILED"
-        echo -e "\"$1\" package is not installed."
-        ask "Do you want to install it now?" "install_pkg $1" || \
-        return 3
-    fi
-    shift
-    echo -e " OK"
-done
+    while (( $# > 0 )); do
+        echo -en "Dependency check for $1 ..."
+        if ! $1 --version > /dev/null 2>&1 && \
+            ! $1 -v > /dev/null 2>&1 && \
+            ! $1 --help > /dev/null 2>&1; then
+            echo -e "FAILED"
+            echo -e "\"$1\" package is not installed."
+            ask "Do you want to install it now?" "install_pkg $1" || \
+            return 3
+        fi
+        shift
+        echo -e " OK"
+    done
 }
